// add any using statements to here to keep everything clean:
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Color = Windows.UI.Color;
global using Colors = Microsoft.UI.Colors;
global using System.Numerics;
global using Microsoft.UI.Composition;
global using Microsoft.UI.Xaml.Hosting;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.IO;
global using System.Collections.ObjectModel;
global using System.Collections.Specialized;
global using System.Text.Json;
global using FoxyBrowser716_WinUI.DataObjects;
global using static FoxyBrowser716_WinUI.Controls.Helpers.Animator;
global using FoxyBrowser716_WinUI.StaticData;
global using Microsoft.UI.Xaml.Data;
global using CommunityToolkit.Mvvm.ComponentModel;
global using Windows.Foundation;
global using FoxyBrowser716_WinUI.DataObjects.Basic;
global using Microsoft.UI.Xaml.Input;
global using Microsoft.UI.Xaml.Media.Imaging;
global using Material.Icons;
